# PD Configuration
initial-cluster-state = "new"

lease = 3
tso-save-interval = "3s"
quota-backend-bytes = "8G"

[security]
cacert-path = ""
cert-path = ""
key-path = ""

[log]
level = "info"

[log.file]

[metric]

[schedule]
enable-one-way-merge = false
leader-schedule-limit = 4
max-pending-peer-count = 16
max-snapshot-count = 3
max-store-down-time = "30m"
merge-schedule-limit = 8
region-schedule-limit = 64
replica-schedule-limit = 64
split-merge-interval = "1h"

[replication]
location-labels = []
max-replicas = 3
